const chromium = require('@sparticuz/chromium');
const puppeteer = require('puppeteer-core');

module.exports = async (req, res) => {
  if (req.method !== 'POST') {
    return res.status(405).send('Method Not Allowed');
  }

  const { name, email, subscriptions } = req.body;

  const html = `
    <html>
    <head>
      <meta charset="UTF-8">
      <style>
        body { font-family: sans-serif; padding: 40px; }
        h1 { color: #007AFF; }
        table { border-collapse: collapse; width: 100%; margin-top: 20px; }
        td, th { border: 1px solid #ccc; padding: 8px; }
      </style>
    </head>
    <body>
      <h1>StackZero AI Report</h1>
      <p><strong>Name:</strong> ${name}</p>
      <p><strong>Email:</strong> ${email}</p>
      <h2>Subscriptions:</h2>
      <ul>
        ${subscriptions.split(',').map(sub => `<li>${sub.trim()}</li>`).join('')}
      </ul>
      <footer style="margin-top: 40px; font-size: 13px; color: #007AFF; text-align: center;">
        Generated by StackZero.ai
      </footer>
    </body>
    </html>
  `;

  try {
    const browser = await puppeteer.launch({
      args: chromium.args,
      executablePath: await chromium.executablePath(),
      headless: chromium.headless,
    });

    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });

    const pdf = await page.pdf({ format: 'A4', printBackground: true });
    await browser.close();

    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', 'inline; filename="report.pdf"');
    res.send(pdf);
  } catch (err) {
    console.error('[PDF Error]', err);
    res.status(500).send('PDF generation failed.');
  }
};
